In [1]:
import numpy as np

arr1 = np.array([1, 2, 3])

print(arr1)

[1 2 3]


In [9]:
print(type(arr1))

<class 'numpy.ndarray'>


In [11]:
print(arr1.shape)

(3,)


In [13]:
print(arr1[2])

3


In [14]:
arr1[2] = 5

In [15]:
print(arr1)

[1 2 5]


In [17]:
arr2 = np.array([[1, 2, 3], [3, 4, 5]])

In [18]:
arr2

array([[1, 2, 3],
       [3, 4, 5]])

In [20]:
print(arr2[1][2])

5


In [21]:
print(arr2.shape)

(2, 3)


In [22]:
arr2[0, 1]

2

In [23]:
arr2[1, -2]

4

In [24]:
arrS = np.array(['China', 'India', 'USA', 'UK', 'Sweden'])

In [25]:
print(arrS)

['China' 'India' 'USA' 'UK' 'Sweden']


In [26]:
arrR = np.arange(0, 20, 2)
arrR

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
print(arrR)

[ 0  2  4  6  8 10 12 14 16 18]


In [28]:
arrL = np.linspace(0, 10, 20)

In [29]:
print(arrL)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [30]:
arr = np.random.rand(10 * 10)
print(arr)

[0.83249966 0.33618665 0.13357145 0.30973497 0.35182404 0.78177196
 0.51155928 0.52909224 0.44007838 0.19435283 0.26626509 0.1206394
 0.41937537 0.10459577 0.74671063 0.46524921 0.01501915 0.3569628
 0.94874693 0.82066595 0.00568977 0.18158525 0.88943832 0.92454219
 0.54407121 0.58407122 0.5375392  0.51085501 0.79839205 0.79606443
 0.61116417 0.16741923 0.72052635 0.52205121 0.33426889 0.65826965
 0.69136968 0.40309173 0.76225248 0.62431399 0.71238243 0.72700575
 0.81069926 0.12442852 0.01156681 0.96338261 0.15735893 0.79119338
 0.27887583 0.24091851 0.0019898  0.98106234 0.5936614  0.33898149
 0.20422073 0.55181165 0.19601919 0.96793156 0.93034493 0.15914462
 0.97815217 0.05237283 0.1905762  0.15961395 0.8315371  0.00575277
 0.75031923 0.26360027 0.87292986 0.60553278 0.29997122 0.49881792
 0.96608235 0.75590659 0.35395217 0.6002366  0.7939617  0.28519699
 0.29598098 0.83237632 0.53476601 0.75349158 0.1123007  0.84402787
 0.68316604 0.67385542 0.2668077  0.50428196 0.23180626 0.567083

In [31]:
arr = np.random.rand(3, 4)
print(arr)

[[0.86708864 0.36018092 0.73707093 0.34062544]
 [0.84475234 0.74534273 0.15602294 0.02271554]
 [0.51684887 0.3641022  0.53327142 0.49106229]]


In [34]:
print(np.zeros(10))
print('/n')
print(np.zeros((2, 3)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
/n
[[0. 0. 0.]
 [0. 0. 0.]]


In [35]:
print(np.ones((10, 10)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [36]:
arr = [0, 1, 2]
print(arr)

[0, 1, 2]


In [37]:
print(np.repeat(arr, 3))

[0 0 0 1 1 1 2 2 2]


In [38]:
print(np.tile(arr, 3))

[0 1 2 0 1 2 0 1 2]


In [39]:
identity_matrix = np.eye[3]
print(identity_matrix)

TypeError: 'function' object is not subscriptable

In [40]:
print(np.eye)

<function eye at 0x000001DCF85E04A0>


In [41]:
identity_matrix

NameError: name 'identity_matrix' is not defined

In [42]:
identity_matrix = np.eye(3)

In [43]:
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [44]:
np.diag([1, 2, 3, 4, 5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [45]:
arr = np.random.rand(5, 5)
print(arr)

[[0.81378403 0.04329931 0.5127288  0.91922472 0.08116307]
 [0.03182934 0.53717849 0.79064655 0.21552168 0.74361751]
 [0.61410937 0.04432458 0.7139554  0.15393216 0.26337851]
 [0.25446821 0.29286591 0.00666684 0.87495699 0.8248972 ]
 [0.90527235 0.0383955  0.95322404 0.98877002 0.68347364]]


In [46]:
np.diag(arr)

array([0.81378403, 0.53717849, 0.7139554 , 0.87495699, 0.68347364])

In [47]:
arr.ndim

2

In [48]:
arr.size

25

In [49]:
arr.shape

(5, 5)

In [50]:
np.random.randint(-10, 10, 6)

array([  1,  -8, -10,  -6,   6,   0])

In [54]:
arr*2

array([[1.62756806, 0.08659862, 1.02545761, 1.83844944, 0.16232614],
       [0.06365868, 1.07435698, 1.5812931 , 0.43104335, 1.48723502],
       [1.22821874, 0.08864916, 1.42791081, 0.30786431, 0.52675701],
       [0.50893641, 0.58573183, 0.01333369, 1.74991398, 1.64979439],
       [1.8105447 , 0.076791  , 1.90644808, 1.97754005, 1.36694728]])

In [55]:
np.exp(arr)

array([[2.25643025, 1.0442504 , 1.66984165, 2.50734574, 1.08454774],
       [1.03234131, 1.71117196, 2.20482149, 1.24050887, 2.10353132],
       [1.84800998, 1.04532159, 2.04205245, 1.16641175, 1.30131918],
       [1.28977554, 1.34026307, 1.00668912, 2.39877212, 2.28164619],
       [2.47260524, 1.03914213, 2.59405955, 2.68792635, 1.9807462 ]])

In [56]:
print(arr)

[[0.81378403 0.04329931 0.5127288  0.91922472 0.08116307]
 [0.03182934 0.53717849 0.79064655 0.21552168 0.74361751]
 [0.61410937 0.04432458 0.7139554  0.15393216 0.26337851]
 [0.25446821 0.29286591 0.00666684 0.87495699 0.8248972 ]
 [0.90527235 0.0383955  0.95322404 0.98877002 0.68347364]]


In [57]:
np.log(arr)

array([[-0.20606027, -3.13961863, -0.66800822, -0.08422466, -2.51129493],
       [-3.44736682, -0.62142485, -0.23490425, -1.53469378, -0.29622847],
       [-0.48758224, -3.11621591, -0.33693478, -1.87124332, -1.33416309],
       [-1.36857938, -1.2280404 , -5.01060885, -0.13358055, -0.19249651],
       [-0.09951944, -3.25981499, -0.04790531, -0.01129351, -0.38056719]])

In [58]:
np.log2(arr)

array([[-0.29728213, -4.52951223, -0.96373215, -0.1215105 , -3.62303274],
       [-4.97349902, -0.89652655, -0.3388952 , -2.21409511, -0.42736735],
       [-0.70343247, -4.49574925, -0.48609414, -2.69963347, -1.92479048],
       [-1.97444268, -1.7716878 , -7.22878054, -0.19271599, -0.27771376],
       [-0.14357621, -4.70291892, -0.06911276, -0.01629309, -0.5490424 ]])

In [59]:
np.log10(arr)

array([[-0.08949084, -1.36351905, -0.29011228, -0.03657831, -1.09064153],
       [-1.49717239, -0.26988138, -0.10201762, -0.66650904, -0.12865039],
       [-0.21175427, -1.35335538, -0.14632892, -0.81267065, -0.57941967],
       [-0.59436647, -0.53333117, -2.17607977, -0.05801329, -0.08360017],
       [-0.04322075, -1.41571966, -0.02080501, -0.00490471, -0.16527823]])

In [60]:
np.sin(arr)

array([[0.72689107, 0.04328578, 0.49055697, 0.7951317 , 0.08107399],
       [0.03182396, 0.51171392, 0.7108082 , 0.21385707, 0.67695491],
       [0.57623085, 0.04431007, 0.65482829, 0.15332497, 0.26034403],
       [0.25173078, 0.28869729, 0.00666679, 0.76751593, 0.73447802],
       [0.78659335, 0.03838607, 0.81528664, 0.83535047, 0.63149023]])

In [61]:
np.tan(arr)

array([[1.05844649, 0.04332639, 0.5629468 , 1.31115347, 0.08134176],
       [0.03184009, 0.59560077, 1.01055225, 0.21892183, 0.9197451 ],
       [0.70505326, 0.04435363, 0.86642978, 0.1551596 , 0.2696424 ],
       [0.26010692, 0.30153659, 0.00666694, 1.19731696, 1.0822913 ],
       [1.27389444, 0.03841438, 1.40795435, 1.51959891, 0.81442275]])

In [62]:
arr

array([[0.81378403, 0.04329931, 0.5127288 , 0.91922472, 0.08116307],
       [0.03182934, 0.53717849, 0.79064655, 0.21552168, 0.74361751],
       [0.61410937, 0.04432458, 0.7139554 , 0.15393216, 0.26337851],
       [0.25446821, 0.29286591, 0.00666684, 0.87495699, 0.8248972 ],
       [0.90527235, 0.0383955 , 0.95322404, 0.98877002, 0.68347364]])

In [63]:
np.sum(arr)

12.301684226502724

In [64]:
np.sum(arr, axis = 0)

array([2.6194633 , 0.9560638 , 2.97722164, 3.15240557, 2.59652993])

In [66]:
np.sum(arr, axis = 1)

array([2.37019993, 2.31879357, 1.78970002, 2.25385515, 3.56913556])

In [67]:
np.min(arr)


0.006666842980664112

In [68]:
np.min(arr, axis = 0)

array([0.03182934, 0.0383955 , 0.00666684, 0.15393216, 0.08116307])

In [69]:
np.min(arr, axis = 1)

array([0.04329931, 0.03182934, 0.04432458, 0.00666684, 0.0383955 ])

In [70]:
np.mean(arr)

0.49206736906010895

In [72]:
np.median(arr)

0.5371784924482533

In [74]:
np.mean(arr)

0.49206736906010895

In [76]:
np.mean(arr, axis = 1)

array([0.47403999, 0.46375871, 0.35794   , 0.45077103, 0.71382711])

In [77]:
np.std(arr)

0.3459665919915634

In [78]:
np.std(arr, axis = 1)

array([0.3619398 , 0.29622683, 0.26126057, 0.34076428, 0.35402965])

In [79]:
np.std(arr, axis = 0)

array([0.33236798, 0.19841033, 0.32669738, 0.36627927, 0.29261605])

In [80]:
np.var(arr)

0.11969288277425688

In [81]:
np.var(arr, axis = 1)

array([0.13100042, 0.08775034, 0.06825708, 0.11612029, 0.12533699])

In [83]:
arr

array([[0.81378403, 0.04329931, 0.5127288 , 0.91922472, 0.08116307],
       [0.03182934, 0.53717849, 0.79064655, 0.21552168, 0.74361751],
       [0.61410937, 0.04432458, 0.7139554 , 0.15393216, 0.26337851],
       [0.25446821, 0.29286591, 0.00666684, 0.87495699, 0.8248972 ],
       [0.90527235, 0.0383955 , 0.95322404, 0.98877002, 0.68347364]])

In [85]:
arr[2:, 2:4]

array([[0.7139554 , 0.15393216],
       [0.00666684, 0.87495699],
       [0.95322404, 0.98877002]])

In [87]:
np.sort(arr, axis = 1)

array([[0.04329931, 0.08116307, 0.5127288 , 0.81378403, 0.91922472],
       [0.03182934, 0.21552168, 0.53717849, 0.74361751, 0.79064655],
       [0.04432458, 0.15393216, 0.26337851, 0.61410937, 0.7139554 ],
       [0.00666684, 0.25446821, 0.29286591, 0.8248972 , 0.87495699],
       [0.0383955 , 0.68347364, 0.90527235, 0.95322404, 0.98877002]])

In [88]:
arr.T

array([[0.81378403, 0.03182934, 0.61410937, 0.25446821, 0.90527235],
       [0.04329931, 0.53717849, 0.04432458, 0.29286591, 0.0383955 ],
       [0.5127288 , 0.79064655, 0.7139554 , 0.00666684, 0.95322404],
       [0.91922472, 0.21552168, 0.15393216, 0.87495699, 0.98877002],
       [0.08116307, 0.74361751, 0.26337851, 0.8248972 , 0.68347364]])

In [89]:
arr

array([[0.81378403, 0.04329931, 0.5127288 , 0.91922472, 0.08116307],
       [0.03182934, 0.53717849, 0.79064655, 0.21552168, 0.74361751],
       [0.61410937, 0.04432458, 0.7139554 , 0.15393216, 0.26337851],
       [0.25446821, 0.29286591, 0.00666684, 0.87495699, 0.8248972 ],
       [0.90527235, 0.0383955 , 0.95322404, 0.98877002, 0.68347364]])

In [90]:
arr[:3,:]

array([[0.81378403, 0.04329931, 0.5127288 , 0.91922472, 0.08116307],
       [0.03182934, 0.53717849, 0.79064655, 0.21552168, 0.74361751],
       [0.61410937, 0.04432458, 0.7139554 , 0.15393216, 0.26337851]])

In [91]:
arr[:3, :].transpose()

array([[0.81378403, 0.03182934, 0.61410937],
       [0.04329931, 0.53717849, 0.04432458],
       [0.5127288 , 0.79064655, 0.7139554 ],
       [0.91922472, 0.21552168, 0.15393216],
       [0.08116307, 0.74361751, 0.26337851]])

In [92]:
arr[:3, :].flatten()

array([0.81378403, 0.04329931, 0.5127288 , 0.91922472, 0.08116307,
       0.03182934, 0.53717849, 0.79064655, 0.21552168, 0.74361751,
       0.61410937, 0.04432458, 0.7139554 , 0.15393216, 0.26337851])

In [93]:
arr = np.array([4, 5, 6, 7, 8])
print(arr)

[4 5 6 7 8]


In [94]:
arr1 = np.append(arr, 9)
print(arr1)

[4 5 6 7 8 9]


In [95]:
arr2 = np.insert(arr, 0, [1, 2, 3])
print(arr2)

[1 2 3 4 5 6 7 8]


In [98]:
arr3 = np.delete(arr2, [0, 3])
print(arr3)

[2 3 5 6 7 8]


In [99]:
arrC = arr3.copy()
arrC

array([2, 3, 5, 6, 7, 8])

In [100]:
arr1 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
arr2 = np.array([[5, 6, 7, 8], [5, 6, 7, 8]])

In [104]:
arr_cat = np.concatenate((arr1, arr2), axis = 1)

In [102]:
print(arr_cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]
